### ISSUE TITLE
when printing labels, the plant code occupies too much space

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#146]
when you print labels the css declares the size reserved to a single label:

    width: 78mm;
    height: 45mm;

the bottom row is occupied by, on the left, the plant code; on the right, the species distribution. plant code goes on one single line, but occupies the whole space above it. the distribution is then limited to the right most area without being able to overflow on the white space left above the plant code.

in most cases all goes well, if the text referring to the distribution fits in the (max) four lines reserved for it
![b](https://cloud.githubusercontent.com/assets/122869/10412241/30d93fd4-6f45-11e5-94eb-5638ad1de399.png)

in other cases the column reserved to the distribution is too narrow and the label overflows the assigned space.

![a](https://cloud.githubusercontent.com/assets/122869/10412229/b0fbc534-6f44-11e5-950d-921b55456419.png)

this is what I would like to have:
![c](https://cloud.githubusercontent.com/assets/122869/10412273/386f53ea-6f46-11e5-864d-b9a1d9ba00dc.png)

**Comment by mfrasca** [comment]
@felipe87, puedes comentar sobre el problema? como son sus etiquetas?

**Comment by mfrasca** [comment]
@felipead87, puedes comentar sobre el tema? como son sus etiquetas?

**Comment by brettatoms** [comment]
This is also why I added the species.label_distribution column b/c these distributions are often too long for the label.

**Comment by mfrasca** [comment]
if we managed to let the distribution also use the space *above* the plant code, it might be fine.
check http://stackoverflow.com/questions/33058120/

**Comment by mfrasca** [comment]
![f](https://cloud.githubusercontent.com/assets/122869/10416883/a8b6571c-6fef-11e5-92fd-652bf7ca6243.png)
