### ISSUE TITLE
most tables have impicit `id` primary key

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#16]
_From @mfrasca on May 6, 2015 16:43_

SQLalchemy models in the plants plugin do not explicitly define a primary_key, so sqlalchemy takes care of it and it adds a `id` column.
this is not practical when selecting/creating objects:
I create/select a Fabaceae family, and since this is the first time, I have to add it to the session.
I do not yet commit the session.
I again create/select a Fabaceae family, but since `family` is not the primary key, I get a different object.
if I do commit the session, then things work fine.
but I do not want to commit the session during a bulk import!

_Copied from original issue: mfrasca/bauble.classic#93_

**Comment by brettatoms** [comment]
The id, _created and _last_updated aren't implicit.  All models inherit from bauble.db.Base whose metaclass is bauble.db.MapperBase which creates the common columns: https://github.com/Bauble/bauble.classic/blob/master/bauble/db.py#L99

**Comment by brettatoms** [comment]
If it helps the current bulk CSV import is defined here: https://github.com/Bauble/bauble.classic/blob/master/bauble/plugins/imex/csv_.py#L220

I made an effort to make it as efficient as possible.

Also, making e.g, `Family.family` the primary key won't really work b/c `family` won't necessarily be unique if you have synonyms and different qualifiers like sensu lato, sensu stricto, etc.

**Comment by mfrasca** [comment]
> The id, _created and _last_updated aren't implicit
sorry, I wrote the issue based on assumptions, then I explored the code farther but I forgot to edit this issue. 

the problem I describe was actually caused by the non-flushing of the objects to the database.
https://github.com/Bauble/bauble.classic/blob/master/bauble/db.py#L224

and, for example:
https://github.com/Bauble/bauble.classic/blob/master/bauble/plugins/plants/family.py#L219

**Comment by mfrasca** [comment]
about the sensu stricto, sensu lato, please also have a look at this other issue:
mfrasca/bauble.classic#86

**Comment by mfrasca** [comment]
fa76ab9370290a752524a562746e00aa70b9006f

**Comment by mfrasca** [comment]
regarding the primary key question,

On 10/05/15 17:11, Brett wrote:
> Also, making e.g, |Family.family| the primary key won't really work b/c
> |family| won't necessarily be unique if you have synonyms and different
> qualifiers like sensu lato, sensu stricto, etc.

in issue mfrasca/bauble.classic#9 and in the milestone 1.2 I'm
considering as composite primary key of the |Taxon| table:

rank, epithet, author, year

although for the rank 'species' and lower I will have trouble, because
the (sequence of) epithet(s) is only unique within the genus. and I do
not know how to model that (yet).

**Comment by brettatoms** [comment]
I guess I don't understand why having an `id` primary key column is a problem.   Trying to work around it and having composite primary keys on every table seems way more complicated.

**Comment by mfrasca** [comment]
I'm not so sure it's a problem as such, but I'm currently working around its presence, because it's a meaningless field and it would be in the way if I would export it in the JSON format exchange files.
