### ISSUE TITLE
python/mako error when trying to run Bauble

### ISSUE THREAD

**Issue by ShaneJL** [Bauble/bauble.classic#165]
Hello all,

Been away from Bauble for a few years, but starting to get back to applying it for record-keeping of a small nursery and revegetation on our property.

Followed the instructions to install dependencies and run devinstall.sh which eventually seemed to go OK (a few drop-outs whilst fetching from git).

when trying to run bauble, got some errors.
this was what it spat out in a terminal (I'm on Ubuntu 14.04) after trying to run:

```
Traceback (most recent call last):
  File "/usr/local/bin/bauble", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mako>=0.2.2
```

Yet, a bit earlier in the terminal in the bauble -u info, it seemed to be happy with finding mako as shown thus:

```
Using /usr/local/lib/python2.7/dist-packages/gdata-2.0.17-py2.7.egg
Searching for Mako==1.0.3
Best match: Mako 1.0.3
Processing Mako-1.0.3-py2.7.egg
Mako 1.0.3 is already the active version in easy-install.pth
Installing mako-render script to /home/summit/.virtualenvs/bacl/bin
```

It also seemed happy with python2.7 in my system.

Not sure if this is the place for bugs/troubleshooting like this or not...

Regards, Shane.

**Comment by mfrasca** [comment]
this is definitely the place. :smile: 
you already had an older bauble on your system, isn't it?
I see bauble installed in `/usr/local/bin/bauble`. you placed the most recent script there, or is this a remnant of the old installation?

`bauble -u` looks for `Mako==1.0.3`

while `bauble` requires (not finding it) `mako>=0.2.2`

**Comment by ShaneJL** [comment]
Hello Mario;

ah, er... yes, OK I admit it.. I have Bauble 1.0.11 floating around... 
BUT... It is in a separate partition /Resources/Bauble/bauble-1.0.11
Since last using that, I'd upgraded Ubuntu from 12.04 to 14.04, and 
whilst it kept a Bauble icon in the launcher (it didn't work) I didn't 
come across much else apart from some simple .bauble config files in my 
home directory. So I didn't go looking further to clean out old stuff, I 
figured a new install would overwrite any old defunct bits.

So perhaps my mistake was not a better clean up to start. I've just 
tried running bauble --purge and --uninstall from the /Resources/Bauble 
location without anything happening - perhaps there isn't an uninstall 
script? I may just have to look further into sys directories to remove 
any old bits causing confusion. I also think the ubuntu paths changed a 
bit between v12 and 14 so that may have further complicated old file 
confusion.

I am fairly sure that the new install using /usr/local/bin/ is OK for my 
system, I think that's the default path for custom(user) installed programs.
At least I know now to use some diligence in tidying up old stuff before 
I bother you again :-) and thanks for clarifying the different calls to mako

-shane.

**Comment by ShaneJL** [comment]
Success.. with this part anyway.

Turns out the /usr/local/bin/ was the old locations; there was also a 
bit of other stuff I cleaned out too. and checked the ubuntu repos, 
found python-mako default install for python3, so also added the other 
one (for python2?), to be sure.
then ran the original shell script again and now can launch Bauble as 
far as putting in db connections.

Before I describe current problems; a note: I have a regular user (my 
daily blunderings) and a super-user (when I want to break things) on my 
computer. So I had to install bauble with sudo command, logged in as my 
super-user. This set up bauble on that user's account, but not my 
regular one. plus, it installed the various files/folders with owner as 
'root' which still gave me problems running it without invoking sudo. 
Fix: simply chown (recursively) to the relevant folders/files, including 
~/bin ~/Local ~/.bauble ~/distlib ~/virtualenvs

Then of course, the way my OS is, I cannot separately install programs 
with sudo as my regular user. Fix: copy (recursively) the above 
files/folders from super user to regular user home directory, chown 
(recursively) to my regular user. Also in the bauble shell script, 
changed the path for the github stuff to match the regular user path.

That lets me launch bauble now as regular user too (though, I will have 
future dramas on my system doing updates, which will be a sudo task 
followed by more manual copying)

So - to the current glitch - after putting in two db options (a new 
sqlite db and connection to existing postgres db), for both of my user 
logins, I got the same error on all 4 occasions:

"Could not load plugins" (and it listed plugins, which I've left off the 
common prefixing of these) .abcd .garden .imex .plants .report 
.report.mako .report.xsl .tag
and then the error message "Cannot import name infixNotation"

Should I put this latest bit, and any of the other install-mods I 
mentioned, in a separate item/bug/etc?

As an aside, does anyone else out there run bauble.classic on a computer 
that has multiple user accounts; if so, what is your approach to installing?
And, what platforms do people use? I've been finding Ubuntu gets bigger 
and fancier than I need each upgrade, it's enough to make me consider 
just going back to a command-line-only OS ;-)

**Comment by mfrasca** [comment]
my current installation policy is in fact user-based, I've given no thoughts to »does anyone else out there run bauble.classic on a computer that has multiple user accounts?«
I'm sorry it was not clear enough, that you do not need become root to install it, and that I do not describe how to achieve a global installation.
I would not use root for a global installation anyway. I would have a user owning bauble, just as there is a user owning postgresql, I could consider this installation "the global installation" and other users could access it if in the same group as this user. but details have to be worked out.
just sharing thoughts.
thanks for the report, it's interesting!

**Comment by mfrasca** [comment]
original issue solved. please open new issue. thanks a lot for your feedback!
