### ISSUE TITLE
how to achieve a global installation

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#167]
mentioned in #165 
the current virtualenv-based installation procedure does not describe how to achieve a global installation.

**Comment by ShaneJL** [comment]
thoughts: I note that for my OS, in ubuntu software repo, there is a download for an old Bauble version. that at least may have some clues as to how it gets installed globally, for ubuntu at least, and perhaps process could be adapted for current version and some Linux flavours.

**Comment by mfrasca** [comment]
I am not the maintainer of the debian/ubuntu package. I've contacted the current maintainer, but I'm afraid we didn't really understand each other on what should be done by whom, in order to have the bauble package updated. have a look at the open issue on launchpad about it: https://bugs.launchpad.net/ubuntu/+source/bauble/+bug/1093035

**Comment by RoDuth** [comment]
How does this currently work on Windoze?  I, unfortunately, have to use Bauble on win at work and have an earlier v1 installed on 2 win vista network stations with my SQLite data on a network drive and both Bauble installs pointing to it.   It must be global as I have several people who access Bauble on these computers, all with separate logins.  They currently can all open Bauble without issue from a desktop icon.  I'm looking to upgrade to the newer Bauble at work (I currently work on the latest version at home on my Ubuntu laptop, one of the things I like about using SQLite db - I can just stick it on a stick and bring it home) but I fear that each time someone new wants access I'd have to go through the install process again and potentially for both computers...  Not so easy when I'm not the one with administrative access, the IT department is in another building 20mins drive away and will only respond if I log a service request!

**Comment by mfrasca** [comment]
when I set up the current installation method, I had not given much thought to installing for multiple users, my approach was : let's see if this works and if it causes problems we will solve them.

so Bauble now uses virtualenv... and a virtualenv can definitely be set in such a way that one user maintains it (read/write access) and all other users can use it (read_only access).

can you have a look at whether it already works on your system? maybe not, if I remember how roaming data was tossed around in Windows (some 20 years ago).

maybe we can just put the global virtualenv next to all other installed programs, meaning you would need administrative access to run the devinstall script. I think it is currently not necessary. I really need a windows machine to test all that I'm writing!

**Comment by mfrasca** [comment]
mentioned in #55

> (In terms of urgency can I add that I am only using the most recent version at home and have not yet upgraded at work due to the lack of a global install option for windows, this would be my most pressing issue right now in terms of work. I have several people who log into my workstation and use Bauble)

**Comment by mfrasca** [comment]
this now has a solution on windows. see the devinstall-finalize.bat
on unix it works if the owner of the virtual environment makes it available to other users. just a matter of setting some read and execute rights to the bauble owner home dir and into their `.virtualenvs/bacl`

all you still miss is a script for activating the virtual environment and start bauble.
this script does not need be any more complicated than:
```
#!/bin/bash
. /home/$BAUBLE_OWNER/.virtualenvs/bacl/bin/activate
bauble
```

**Comment by mfrasca** [comment]
I was considering, on Unix... what about the `devinstall.sh` script takes a new `--global` option?

the effect of this option would be:
- create a `bauble` user group
- to all the files in the virtualenv: set the group to `bauble`
- to all the files in the virtualenv: set permissions as `g-w+rX,o-rwx`
- create a `/usr/local/bin/bauble` script as of the previous comment

all users in the `bauble` group would be able to run bauble,
only the owner of the virtualenv would be able to update it,
users not in the `bauble` group would not be able to run that installation.

**Comment by mfrasca** [comment]
```
sudo addgroup bauble 2>/dev/null 
sudo usermod -a -G bauble $(whoami)
chmod -R g-w+rX,o-rwx .virtualenvs/bacl
sudo chgrp -R bauble .virtualenvs/bacl
```
