### ISSUE TITLE
bulk editing

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#180]
_From @mfrasca on April 20, 2015 16:41_

is it possible to bulk edit objects? something like, one needs to move a whole group of plants from one location to the other. it can really be a huge lot of them, so this would save us boring tasks.

_Copied from original issue: mfrasca/bauble.classic#54_

**Comment by mfrasca** [comment]
should be careful with possible excesses, like moving a (whole group of) plant identification from one species to the other. 
the above sounds like a misuse, imagine that the point was that a whole group of plants had been identified so some species and then the species are marked as synonym of one other single species: you do not necessarily need change the identification.
but for locations no: I consider it a legitimate request.

**Comment by RoDuth** [comment]
@mfrasca Is there a similarity here to my comments on repeated source info for multiple accessions in issue #159 ?

**Comment by mfrasca** [comment]
this one is about modifying a group of already existing objects. think of this as applying a transformation to all objects of a set, like move everything that is on this table to that other table without changing relative positions.
#159 looks like specifying the position of something which did not yet have any, which possibly did not even exist before the bulk edit action.

**Comment by mfrasca** [comment]
This issue was moved to Ghini/ghini.desktop#84
