### ISSUE TITLE
collection and propagation, do they make sense together?

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#187]
_From @mfrasca on April 29, 2015 20:50_

when specifying a source for a species accession, you can add 'collection' and 'propagation' data, it's not totally clear to Felipe (nor to me) why one would want to add several collection sources and also several propagation sources. isn't one enough?

_Copied from original issue: mfrasca/bauble.classic#81_

**Comment by sehrgut** [comment]
On the "yes, they make sense together" side, I can think of the case where the accession is a propagation based on a parent or parents of known wild collection by the source individual. You wouldn't want to lose this information, or relegate it to freeform comments.

**Comment by mfrasca** [comment]
@felipead87 :bell: (ping)

**Comment by RoDuth** [comment]
I'll second that.  We often collect seed from the wild then propagate it.  As do our volunteers that donate plants.  So we can have a "Source" as a person's name (a volunteer for instance) or an in-house collection trip, the "Collection" being the place they collected the seed and "Propagation" being the treatments, when they sowed, etc.  From my experience you can only add one collection and one source, Bauble doesn't allow more.
