### ISSUE TITLE
species editor window expanding too far

### ISSUE THREAD

**Issue by RoDuth** [Bauble/bauble.classic#197]
Discovered this minor annoyance today when I made an error with cutting and pasting a species name in. I must have grabbed a long string of text by mistake and this made the window expand off the edge of the screen due to the display of the full name at the top of the tab.  This pushed the cancel, OK, etc. buttons of the edge of the screen making it hard to get get out of.  Could this just need word wrap for the full name or the window to be size constrained?  Also I could only get rid of the extra wide window by restarting bauble (i.e. the next time I opened the species editor it was the same extra wide size)

**Comment by mfrasca** [comment]
set priority to high because of the "I could only get rid of the extra wide window by restarting bauble".

**Comment by mfrasca** [comment]
replicate this by opening the species editor, start typing in the species epithet field, insert a very long sequence of characters. this will indeed make the window grow wider to fit the resulting binomial name plus author.
on Linux (ubuntu 14.04), next time you open the species editor window, it will fit the max screen width (which is more workable than the reported behaviour, but still is the desired behaviour).

**Comment by mfrasca** [comment]
the behaviour is now to limit the width of the window to the screen width. 
no change if you do not let the window grow to exceed the screen width.
next time you activate the window, it will either be the previous size, or the screen width.
you can then resize it according to your preference.

**Comment by mfrasca** [comment]
I reverted this patch, and just set the label property "wrap".
