### ISSUE TITLE
Species editor synonym warning not working

### ISSUE THREAD

**Issue by RoDuth** [Bauble/bauble.classic#198]
Species editor does not warn of genus synonyms if opened by right clicking a genus in the search results and selecting add species.  E.g. if I search for *Aladenia* and right click it in the results window it doesn't warn me that *Farquharia* is the accepted genus name.
![species editor from search](https://cloud.githubusercontent.com/assets/15710055/11422444/aa7b1594-9487-11e5-97f5-537a41e52f8a.png)

Also, when I inserting a species from the menu, type and select *Aladenia* as the genus, the synonym warning comes up, I select "yes" (I would like to use *Farquharia* instead) *Farquharia* appears in the genus field but remains red as if the genus doesn't exist, the full name doesn't display, and it wont let me click OK. 
![species editor](https://cloud.githubusercontent.com/assets/15710055/11422537/626ecf10-9488-11e5-9353-e81597fc00d2.png)

**Comment by mfrasca** [comment]
looks related to the way the completions are populated.
