### ISSUE TITLE
Mario can't write on bauble-news.blogspot.com

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#199]
hi @brettatoms ! can you help me with this one too?
https://support.google.com/blogger/answer/41448?hl=en

**Comment by mfrasca** [comment]
https://www.blogger.com/profile/16606681606186666487

**Comment by brettatoms** [comment]
I added you as an author.

What do you think about using something like Nikola (https://getnikola.com/) or Jekyll and hosting the blog/news together with the rest of the site at bauble.github.io?  I could also alias bauble.io to bauble.github.io.  I think that would be better than having two separate sites.

**Comment by brettatoms** [comment]
Just realized that bauble.io is already aliased to bauble.github.io.

**Comment by mfrasca** [comment]
bauble.io == bauble.github.io, how does that work? just gratis et amore Dei?

we have indeed spread the task to maintain quite a few different information sites talking about Bauble, like bauble.io, wikidot, blogspot, google groups, belizebotanic, readthedocs, facebook, and then github plus launchpad... (did I forget some?) it's quite a task to keep track of all of them!

bauble.io I'm now using for "the" bauble web site.
I consider readthedocs the only right place for hosting our documentation.
google groups offers a very approachable alternative to issue opening.
blogspot could fit in "the" bauble web site, as you say.
facebook I started using for publishing news. it has the advantage above blogspot that you can see who like it, and you can contact them.
wikidot now only contains links to other sites, it could be more compact and clear. I don't think I can put a redirect there, can I?
belizebotanic I would replace with a redirect to bauble.io.

**Comment by mfrasca** [comment]
but the issue I was referring to, you solved it! thanks! cheers, M
