### ISSUE TITLE
emergency downgrade

### ISSUE THREAD

**Issue by felipead87** [Bauble/bauble.classic#208]
While perfoming any search with valid results a message ocurres informing that phyton.exe has stopped working. Details of the problem above. This problem ocurred after actualization to v1.0.53
Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	pythonw.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	5488ac31
  Nombre del módulo con errores:	libgdk-win32-2.0-0.dll
  Versión del módulo con errores:	2.24.0.0
  Marca de tiempo del módulo con errores:	4d5fa757
  Código de excepción:	c0000005
  Desplazamiento de excepción:	00021221
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	12298
  Información adicional 1:	0a9e
  Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
  Información adicional 3:	0a9e
  Información adicional 4:	0a9e372d3b4ad19135b953a78882e789

Lea nuestra declaración de privacidad en línea:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0c0a

Si la declaración de privacidad en línea no está disponible, lea la declaración de privacidad sin conexión:
  C:\Windows\system32\es-ES\erofflps.txt

**Comment by mfrasca** [comment]
which version were you using before updating to 1.0.53?

**Comment by felipead87** [comment]
1.0.50

**Comment by mfrasca** [comment]
do you know how to downgrade? it's possible, not totally immediate, but possible.

**Comment by mfrasca** [comment]
before downgrading, you could try to update your python to 2.7.10

**Comment by felipead87** [comment]
python upgrade didn't work, how do I downgrade bauble?

**Comment by mfrasca** [comment]
Feli, puedes ir en una chat? es un poco largo el proceso y más interactivo de lo que podemos hacer en github. skype o gtalk.

**Comment by TatiJaramilloV** [comment]
Está ya en Skype

On Tue, Dec 1, 2015 at 3:55 PM, Mario Frasca <notifications@github.com>
wrote:

> Feli, puedes ir en una chat? es un poco largo el proceso y más interactivo
> de lo que podemos hacer en github. skype o gtalk.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bauble/bauble.classic/issues/208#issuecomment-161093104>
> .
>



-- 

*_________________________*

M.Sc. Tatiana S. Jaramillo Vivanco
*Directora Técnica*


*Jardín Botánico de QuitoTel. 593 997679200Quito-Ecuador*

**Comment by mfrasca** [comment]
solved doing this:
```
@echo off
ECHO downgrade to bauble-1.0.50
call .virtualenvs\bacl\Scripts\activate.bat
cd Local\github\Bauble\bauble.classic
git pull
git checkout 2908f56c88ae2fa13f59cb205d722415ddb183b4
python setup.py install
cd %HOMEDRIVE%%HOMEPATH%
deactivate
```

**Comment by mfrasca** [comment]
@felipead87 , can you make a complete installation on a clean machine, but using Python 2.7.10 or higher? I think you are on 2.0.9, isn't it?
