### ISSUE TITLE
lexicographic position of Genus sp 

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#210]
the sp behind genus is now not correctly handled: it is not part of the species name as if it was a binomial name, it's just an indicator to signify that the species is not known.
as such, »_Anguloa sp_« should really be »_Anguloa_ sp« (sp not italicized).
also, it should precede all other species in the genus.

**Comment by RoDuth** [comment]
Seems to work for me if I put the `sp,` in the epithet field rather than the species field.  Maybe not ideal but it works for now.

**Comment by mfrasca** [comment]
nice one. so to solve the (sp not italicized) part, the advice would be in this case to use the `infraspecific parts`.
![screenshot from 2015-12-09 10 38 45](https://cloud.githubusercontent.com/assets/122869/11689718/262e2644-9e61-11e5-8de2-6c40708b8de8.png)

we still need see how to have the correct lexicographic order.
![untitled](https://cloud.githubusercontent.com/assets/122869/11689847/ba1254b6-9e61-11e5-95ac-86681d307120.png)

**Comment by mfrasca** [comment]
could place it at the end, by prefixing the unranked epithet with a [_zero width space_](http://www.fileformat.info/info/unicode/char/200B/index.htm) (unicode 200b).
![untitled](https://cloud.githubusercontent.com/assets/122869/11696890/afd51bc8-9e84-11e5-8550-80e41fa9e48b.png)

**Comment by felipead87** [comment]
I agree, would be better to have sp on top of the list, it would make it
easier to access

2015-12-09 15:21 GMT-05:00 Mario Frasca <notifications@github.com>:

**Comment by mfrasca** [comment]
I don't see how to do this in an easy way.
at the moment it looks like they will follow the completely specified taxa.

**Comment by mfrasca** [comment]
I don't like it myself! :unamused:

**Comment by mfrasca** [comment]
![untitled](https://cloud.githubusercontent.com/assets/122869/11701064/6ca31226-9e9b-11e5-8aac-eaa1f81797e7.png)

**Comment by RoDuth** [comment]
@mfrasca should cases such as this be in the documentation somewhere? i.e. explaining the use of the epithet field in this scenario.  

I feel that the documentation could be a little more thorough when it comes to getting started entering data.  Seems to stump new users, especially if they have no or little botanic records experience. I have a volunteer whom I am training to do some data entry for me, she has been writing herself notes and making a bit of an internal "guide to Bauble".  Maybe I could ask her to use some of this guide to expand the readthedocs documentation?  I'm just not sure how to go about editing the readthedocs documents myself!  What do you think?  If you do think it could be useful, before I look into it myself, any pointers?

**Comment by mfrasca** [comment]
> I have a volunteer whom I am training to do some data entry for me, she has been writing herself notes and making a bit of an internal "guide to Bauble".
WOW. this sounds great!

if she's willing to edit the docs directly, the best way to do so according to how github works is:
- get a github account
- fork the repository you want do contribute to
- edit, commit, tell me.

to edit things you have a choice of working purely online directly on github, in your forked repository hosted there, or cloning the repository to your machine, edit, commit, push to github, tell me. if you have a reliable internet connection, the online is probably the easiest way to go.

guidelines for documentation writers?

short paragraphs (in relation to translation).
learn that small bit of restructured text syntax that you see elsewhere in the docs.
