### ISSUE TITLE
missing genus hybrid indicator

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#211]
Brassocattleya and Dracuvallia should really have a »×« preceding the epithet.
one more issue that would be solved if we represented family/genus/species as taxon.

**Comment by RoDuth** [comment]
ITF2 Intergeneric Hybrid Flag??    Yes please!

(I get a little concerned that your desire to "flatten" the data structure with "taxon" for family/genus/species is a fairly significant break from any off the botanic record systems I have seen over the years, but, as long as it is easy enough to get the data out in a ITF2/ABCD/etc. compatible format, e.g. for [PlantSearch](http://www.bgci.org/resources/plantsearchuploadinstructions/) updates, I guess its no big deal?)

**Comment by mfrasca** [comment]
currently `Genus.hybrid_marker`, the genus hybrid indicator, is computed from `Genus.genus`: 

if Genus.genus contains a `×` then it's `H`
if Genus.genus starts with `x` or `×`, then it's `×`
if Genus.genus starts with `+`, then it's `+`

correspondingly, `Genus.epithet` is computed removing any leading `x`, `×`, `+`.

these fields are available in reports, not in queries.
you can search for hybrid marker using the `like` construct:
`genus where genus.genus like '×%'`

**BIG FAT BUT**
but the data we use to initialize the database does not contain that leading `×` nor `+`.

**Comment by mfrasca** [comment]
This issue was moved to Ghini/ghini.desktop#7
