### ISSUE TITLE
example of another project accessing taxonomic data from the web

### ISSUE THREAD

**Issue by tmyersdn** [Bauble/bauble.classic#214]
@mfrasca @RoDuth

https://github.com/inaturalist/inaturalist

This project was recommended to me by someone working on the ALA project as a potential way to capture botanic garden data. The main problem is that each observation is (to my knowledge) treated as unconnected, and as having no "history" (ie no source of the object observed, no obvious facility for serial observations), for this reason it is not suited (as it stands) for apply to botanic garden data, although I am sure it will eventually gain this capability.  It raises the possibility that visitors to a garden will be soon be able to interact directly with garden plant records, and to record observations, not just staff. This is alongside wild observations of birds, insects, whatever. Adding observations with images can lead to direct feed back from other expert users on identification.
I am drawing your attention to it because it routinely expects users to select a name from a web source, or to choose to enter a name that is not verified. In this way it is rather rigid, as it expects you to accept an externally provided taxonomy. This is restrictive as it removes the flexibility that may be required by a botanic garden with a specialist collection.

**Comment by mfrasca** [comment]
it is indeed a nice web site, but I am not so sure what to look for in it. what part of their functionality to you think you would like to see in Bauble too?

**Comment by RoDuth** [comment]
I think @tmyersdn was just pointing to the way it drags names from web resources...

**Comment by tmyersdn** [comment]
@mfrasca, @RoDuth 

Several issues here:
(1) as Ross says, it is a working example of an app drawing in name data from external sources, in particular Catalogue of Life.

(2) Not just names, but also higher taxonomy. Mario, I believe this app has some functions which strongly relate to your interest in handling data on higher taxonomy. If you look at section 3 of the report link (http://www.inaturalist.org/observations/export?projects%5B%5D=korean-nature), you get the option of exporting higher taxon data, which I guess comes from Catalogue of Life (see http://www.catalogueoflife.org/webservices/ for details of XML schema).

(3) Future proofing bauble - incorporating catalogue of life (etc) permalinks or lsid could prove useful for later connectivity and tools. And, the ability to work with XML schema is also of interest. Ross has talked about exporting data to BGCI Plant Search, but gardens could also want to export data to their national GBIF node.
