### ISSUE TITLE
windows install instructions

### ISSUE THREAD

**Issue by tmyersdn** [Bauble/bauble.classic#215]
for dummies..
Clarify and add links for point 9 on Windows install notes on introduction page :-) for those of us stuck with windows...

**Comment by mfrasca** [comment]
well, you say "for dummies"... I was so happy to have reached point 8 in the installation procedure and to be able to stop looking at Windows, that I did not care properly completing my task.
I now think that step 9 should be taken care by `devinstall.bat` itself.
moreover, `devinstall.bat` is the place where the user is offered the choices I mention in #216.
so I just need look at Windows a bit longer I'm afraid!

**Comment by tmyersdn** [comment]
many thanks!

**Comment by mfrasca** [comment]
http://i-broke-it.blogspot.pe/2010/04/taming-all-users-desktop-and-start-menu.html

**Comment by mfrasca** [comment]
wondering whether this might be acceptable:
- you run the (modified) `devinstall.bat` script according to the current instructions.
- this will generate a `devinstall-finalize.bat` script in your home directory
- run as administrator the `devinstall-finalize.bat` script (from the file browser, right click on the file, select _**Run as administrator**_, say you trust me).
- this will add the Bauble shortcut to the Start Menu for all users.

step 9 would be modified accordingly.

I guess the Windows style of writing installation scripts is totally something different.

**Comment by mfrasca** [comment]
@tmyersdn : can you check if they (instructions and script) work for you?
I plan re-writing the NSIS installation procedure, so that it will do exactly what the current batch-based installation procedure does, but within one single Windows installer.
#219

**Comment by tmyersdn** [comment]
@mfrasca, apologies, I ran into a snag, need to get laptop admin to authorize (I did say for dummies), this may take until after Xmas to organize. But will try soon. Move on for now, I will help when able.

**Comment by tmyersdn** [comment]
@mfrasca, I think this raises the point of permissions, I am using a non-networked work laptop to look at Bauble, I have adequate permission to install packages, but not to run the install script (see "final caveat" blog you mention above).   Is it possible to include this elevated admin requirement in the install instructions, ie part of the requirements for installing the software?  Also, perhaps the batch scrips could include testing for adequate permission status, and give a message if insufficient status?

**Comment by mfrasca** [comment]
Tom, not to play the Windows hater, but [this is again one more reasons](http://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights) why I dislike it!
I will document something like "If you run the `devinstall-finalize.bat` script with Administrator permissions, it will make your Bauble installation visible to all users, otherwise it will be available to yourself only".

**Comment by tmyersdn** [comment]
Mario, I don't disagree, but this problem with permissions is exactly why city run IT departments like Windows, it gives them control. I will predict that it is one reason why not many gardens are not trying Bauble, and it is why I advocate moving to a web based platform (ask @RoDuth).  If you want to engage with many botanic gardens, and  you don't like Windows, then you need to move to web based.  I have found from 20 years experience that IT departments do not understand or care about our software, and that permission issues predictably cause major problems. 
This is not a level playing field, many of us do not have access to installing and managing our own software, and we certainly don't get to choose our operating systems.

**Comment by tmyersdn** [comment]
@mfrasca, thanks for adding the extra text above, the problem I have is that the devinstall-finalize.bat does to appear to run, or fails without error message, as the virtual environment is not set up, hence when I thought I was failing at step 9 (running Bauble), I was actually failing at step 7.
I need to follow up this permission issue with our IT department, but I am on leave this week so it will have to be next week.  We have an old mac at home which I will try in the meantime, just need to install xcode..

**Comment by mfrasca** [comment]
(about permissions) ... oh, sorry, I obviously was not clear except to myself! Unix (an in particular Linux), just like all decent operating systems, has permissions management and it works quite uniformly in all Unix flavours, including MacOSX. my trouble with Windows is that it implements it in its own way which is totally not compatible with Unix and also quite often not compatible with any previous version of Windows. so one stays busy thinking one's learning something, but one's just coping with the "moving target" environment named Windows.
and yes, I know that my freedom as software developer is limited to the choices taken by IT departments. so I develop stuff on Linux and make sure it's portable to Windows (except the installation procedure!)

**Comment by mfrasca** [comment]
Mac? how old? please keep me up to date, and note down all that does not match reality in the instructions!

**Comment by mfrasca** [comment]
(about step 7) :: can you be as awfully specific as you possibly manage, with what went wrong with step 7? (remember that all successes are alike, but failures follow the Anna Karenina principle).

**Comment by tmyersdn** [comment]
10.6.8, but will probably have to upgrade to the new el capitan if that is possible, to access a free xcode, or can go back to xcode 3.2.6, but it takes an hour to download, and I would prefer to upgrade if that is possible.

Step 7:  am just answering this from memory, but will look again next week when I am back at work. My memory is that there was an error message about running again as admin.  Sorry, should have copied and sent that to you.
Also, is it possible to add a note for this instruction about which interface to run the devinstall.bat in? I ended up settling on the GUI, but this was after trial and error. (remember, steps 1 to 5 have the end user installing quite a few items.
In general I find your instructions very good, and I prefer this step by step approach, which I believe is more instructive than a batteries included install.
Okay, better keep tidying here, I am heading away tomorrow!

**Comment by mfrasca** [comment]
step 7: something like this?
![screenshot from 2015-12-16 22 10 13](https://cloud.githubusercontent.com/assets/122869/11875181/71de2d86-a4b1-11e5-9804-0b4d0ba2546a.png)

**Comment by RoDuth** [comment]
@tmyersdn I still think that in the long run a batteries included install is the way to get increased uptake.  Think about it like this.  You can get BGRecorder and just start using it.  You don't even need to install it, it just runs straight from the file (and in Queensland at least there are several flavours floating around).  Same with the PV database.  Same with any of the Excel solutions out there.  Then you decide to try Bauble and after a day of trying to work out how to install it you still cant get it running....   Which one looks more attractive to the non tech savvy who just wants a simple solution (i.e. not IRIS or BGRecorder etc.) to start record their collection?  That's potentially a big part of the target group.  I just think that there are a lot of potential users out there who aren't comfortable with this kind of process.  Who would balk at it, fearing that they might damage there systems because they don’t understand what they are doing.  Just a comment for the future relating to issue #155

**Comment by tmyersdn** [comment]
@mfrasca 
Finally got back to this issue... thanks for image above

For instruction 7, can you add text like 
"7.download and run the batch file (from \system32\cmd.exe): devinstall.bat"

Failed results: see screen capture
![capture](https://cloud.githubusercontent.com/assets/15988432/11969236/b3318c28-a97b-11e5-8335-cb5cba848cae.JPG)

**Comment by mfrasca** [comment]
»Couldn't resolve host 'github.com'«
looks like you are behind a very tight firewall, or have an issue with your local proxy configuration.

if it's just a DNS problem, you might even try editing the `devinstall.bat` file and replace `github.com` by its numerical address (`192.30.252.130`), but I think the real solution is to ask your network administrators.

```
mario@rune:/tmp$ dig github.com | grep -A1 ANSWER.SECTION
;; ANSWER SECTION:
github.com.		15	IN	A	192.30.252.130
```

**Comment by mfrasca** [comment]
or... you might try to change https to http?

**Comment by tmyersdn** [comment]
hah, okay, found internet connection, please add to your instructions: "connect to the internet"

But still getting the other errors - see below
![error](https://cloud.githubusercontent.com/assets/15988432/11970297/6b584bbe-a98d-11e5-951f-839c1a990c69.JPG)

**Comment by mfrasca** [comment]
"connect to the internet" :laughing: 
are you quite sure you followed »when installing Python, do put Python in the PATH« on step 2?

**Comment by tmyersdn** [comment]
I did say "for dummies", thanks Mario, will follow this up tomorrow..

**Comment by RoDuth** [comment]
.... @tmyersdn I think your proving my "batteries included" comment above :laughing:

Your more dogged then most! :smile: 

But it does prove the point of the limitations we have due to restrictive access....  One of the reasons I still haven't upgraded at work is I don't see the virtual environment working in my restricted work set up.  Would be fine for me maybe but not anyone else!

**Comment by mfrasca** [comment]
> proving my "batteries included" comment above

I agree with you @RoDuth , that would be issue #219 ... and I hate that task! :grin:

**Comment by tmyersdn** [comment]
@mfrasca, @RoDuth 
I guess you would create "batteries included" versions for just the most recent "milestone" or showcase versions. Otherwise the workload would be too great.

Okay, Xmas eve here and we finish work in 15minutes.  Apologies, I had meant to comment more on scope and the new interface which is great, however, for now I have stuck to the windows install.  Ross, I still think it is great to offer this non-batteries access to the development process.

Mario I have corrected step 2 as you suggest, and redone step 3 as well for good measure.  I am running Windows 7, so have ignored step 4.  Done a reboot because this is windows.

Okay, I am seeing a lot more happening in devinstall.bat, too much to do a screen grab.  Is it possible to export to a text file (I see echo > FileName.txt should write to file, but does that also output the results?).  I suggest, that as the results of the devinstall are diagnostic of install problems, that saving the results should be standard.

Now I am stuck on step 8, as there is no batch file "devinstall-finalize.bat" in my home folder (assume you mean user folder from which I ran the devinstall.bat?). I will catch up on this in four days time, in the meantime, I hope you have a great holiday.

![bat](https://cloud.githubusercontent.com/assets/15988432/11986148/2358c5d8-aa31-11e5-89ca-2e5aa9c9c729.JPG)

**Comment by mfrasca** [comment]
I don't know why you did not get the `devinstall-finalize.bat` script. it should be created by running the latest version of `devinstall.bat`, maybe you had downloaded it too early?

I can't copy mine for you here, because paths will not be correct, but I can pass you a small script that will produce it for you with all correct paths, notice you need run it as Administrator!

[create-finalize.bat](http://bauble.io/resources/create-finalize.bat)

**Comment by mfrasca** [comment]
about the seeing the output of a batch file and copying it to a file at the same time, that's standard on Unix and difficult on Windows.
http://stackoverflow.com/questions/11239924/windows-batch-tee-command

**Comment by tmyersdn** [comment]
thanks Mario, the create-finalize.bat worked well, and I have got Bauble running :)

thanks also for comment on batch files, in principle errors should not happen if the earlier instructions are followed correctly, but I am guessing some users (like me...) don't realize they have made mistakes until the batch files don't run properly.  Someone I work with is also trying an install on Windows 8, so will see how they go.

**Comment by mfrasca** [comment]
hi Tom. good that you have good news. after all this experience I think I can note down for myself:
- add sanity check in devinstall.bat
- move scripts to bauble.io/resources/
