### ISSUE TITLE
flexible import of csv exports

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#222]
@RoDuth writes in #55:

> When I say csv dump I'm more thinking about the kind of output you can get from the reporting system (where you only output selected fields from the search results, etc.) just there is no way of importing this at this point. (e.g. If I have a batch of seedlings from a known collection source and I use half of them for a new accession for us and give the other half to another garden, I can pull our records up in Bauble and generate a report which provides our accession number, all the collection data and any other fields that may be of relevance to the receiving garden. Then when they get it, if it is in some universal format such as csv, they could import it into their database when they generate their accessions) And in this context I say csv only as it is so universally used. Its more the scenario that interests me and from our discussion the other day I think I remember you talking along the same lines in regards to the use of JSON. I have absolutely no JavaScript or JSON understanding so wont proffer a solution here but is there a way to make the 2 work together? I think most systems are able to produce a basic csv - can this be transformed, say using a script for instance, into JSON? Anyway, I'm out of my depth here, you get the point. Just looking for as universal a solution as possible.

**Comment by mfrasca** [comment]
Ross @RoDuth, this is the reason why I often repeat that a group of gardens should adopt Bauble and temporarily hire a programmer.
the JSON import-export tool came out of the JBQ period, and it's been useful to them and I'm using it extensively to import data into existing databases, but it does not import-export all the fields of all the database objects: only the ones the JBQ was interested in at the time we migrated their data. see for example #206.
what about you give me an example csv export as the one you mention, then I can tell you more. maybe it's just ½ hour work, or less than one day, just the time to write an external script, if the fields are already included in the current JSON export? if they're not included then no, it will take less than a week but more than a day.

**Comment by RoDuth** [comment]
I agree, it would be ideal to have a group of gardens.  Not sure I am of much use in that regard, we have shared material with several gardens in the past but not repeatedly from any particular garden and I think they are all settled on the systems they use anyway.

I will see what I receive from ANBG and get it to you soon hopefully.  I might see if I can get another example from one of the gardens that uses BGRecorder also.  (Assuming then can provide it)

**Comment by mfrasca** [comment]
This issue was moved to Ghini/ghini.desktop#127
