### ISSUE TITLE
batch taxonomic check information with tnrs

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#229]
- this issue (229) is about batch correction of taxonomic information _post facta_.
- related issue #225  is about sending taxonomic information to an external service — which might send a report back, possibly triggering corrections in the data.
- related issue #221 describes the verification of the information being inserted in the species editor window, while it is still open.

splitting from #221 
copying here the relevant comments there and removing them from that issue.

this issue is about correcting a whole batch of **species** entries, which might be missing authorship info, have typing mistakes in the species and even in the genus epithet.

what I here propose is a new still unnamed tool in the `Tools` menu.

**2015-12-18 08:41-0500**
I'm not so sure this what you mentioned is the same, or just similar to, the lookup functionality at http://tnrs.iplantcollaborative.org/TNRSapp.html
this one is quite good, the only missing thing is the web-api.
without a web-api, the user would need do a couple of manual steps, not so terrible according to me:
- select the things to check (this in any case)
- export with a report that will just print the genus and species epithets.
- open the above page
- paste the output into the search form
- submit list
- wait
- download results
- import the results into Bauble

what is missing?
- the export, "report that will just print the genus and species epithets".
- the import, the TNRS results.
- show a report informing the user about success and failures of the import.
- the graphical interface to all this

**2015-12-18 11:55-0500**
this might show what I mean: ca63eae
the data contained simple mistakes like misplaced h, or missing i in double ii, things like that.
with the help of TNRS, of the ~350 cases, we went down to 9.

**2015-12-18 17:14-0500**
the easiest I can imagine is: 
- you do a selection
- you start Bauble's taxonomic check tool.
- Bauble exports the relevant information into the clipboard,
- Bauble opens the tnrs page.
- you need to paste the info,
- you need request the export.
- when you are offered to open the file, do I dare promise a `bauble_client`? a program that receives the file then contacts the correct running Bauble instance and passes it the information. let's say not yet.
- you save the export,
- go back to Bauble
- you request Bauble to run the second part of the taxonomic check tool
- Bauble does what I already wrote (ca63eae) but with enough safety nets.
- Bauble shows a report which you can copy to the clipboard.

**2015-12-20 17:16-0500**
closing the day, I'm having a look at what it might mean, to correct a whole batch of species.
those having overall score 1, fine, this is useful for completing the data like authorship.

all with overall score less than 1 I would not dare send automatically to the program.
somehow the user should have a look at them and check what they want to import and what not.

the following cases seem obvious: you need correct your data:
```
1	Adiantum capillus-Veneris	0.82	Adiantum capillus-veneris	species	1	L.	http://www.theplantlist.org/tpl1.1/record/tro-26602671;http://www.tropicos.org/Name/26602671;http://plants.usda.gov/java/profile?symbol=ADCA	L.	0.11			Pteridaceae	Adiantum	1	capillus-veneris	1									Accepted	Adiantum capillus-veneris	L.	species	http://www.theplantlist.org/tpl1.1/record/tro-26602671;http://www.tropicos.org/Name/26602671;http://plants.usda.gov/java/profile?symbol=ADCA	Adiantum capillus-veneris	Pteridaceae	true	tpl;tropicos;usda	 	
8	Anthurium andranum	0.96	Anthurium andraeanum	species	0.96	Linden ex André	http://www.theplantlist.org/tpl1.1/record/kew-10633					Araceae	Anthurium	1	andraeanum	0.8									Accepted	Anthurium andraeanum	Linden ex André	species	http://www.theplantlist.org/tpl1.1/record/kew-10633	Anthurium andraeanum	Araceae	true	tpl	 	
15	Astrocaryua malybo	0.99	Astrocaryum malybo	species	0.99	H.Karst.	http://www.theplantlist.org/tpl1.1/record/kew-17547					Arecaceae	Astrocaryum	0.91	malybo	1									Accepted	Astrocaryum malybo	H.Karst.	species	http://www.theplantlist.org/tpl1.1/record/kew-17547	Astrocaryum malybo	Arecaceae	true	tpl	 	
```

but number 15 becomes less obvious considering there is already an _Astrocaryum malybo_ in the database. so you need to edit things by hand, even for a close-to-perfect match of 0.99.

- skip infraspecific information
- [gtk.Clipboard.set_text](http://www.pygtk.org/pygtk2reference/class-gtkclipboard.html)
- skip genus results
- let user check line-by-line

**Comment by mfrasca** [comment]
closing the day, I'm having a look at what it might mean, to correct a whole batch of species.
those having overall score 1, fine, this is useful for completing the data like authorship.

all with overall score less than 1 I would not dare send automatically to the program.
somehow the user should have a look at them and check what they want to import and what not.

the following cases seem obvious: you need correct your data:
```
1	Adiantum capillus-Veneris	0.82	Adiantum capillus-veneris	species	1	L.	http://www.theplantlist.org/tpl1.1/record/tro-26602671;http://www.tropicos.org/Name/26602671;http://plants.usda.gov/java/profile?symbol=ADCA	L.	0.11			Pteridaceae	Adiantum	1	capillus-veneris	1									Accepted	Adiantum capillus-veneris	L.	species	http://www.theplantlist.org/tpl1.1/record/tro-26602671;http://www.tropicos.org/Name/26602671;http://plants.usda.gov/java/profile?symbol=ADCA	Adiantum capillus-veneris	Pteridaceae	true	tpl;tropicos;usda	 	
8	Anthurium andranum	0.96	Anthurium andraeanum	species	0.96	Linden ex André	http://www.theplantlist.org/tpl1.1/record/kew-10633					Araceae	Anthurium	1	andraeanum	0.8									Accepted	Anthurium andraeanum	Linden ex André	species	http://www.theplantlist.org/tpl1.1/record/kew-10633	Anthurium andraeanum	Araceae	true	tpl	 	
15	Astrocaryua malybo	0.99	Astrocaryum malybo	species	0.99	H.Karst.	http://www.theplantlist.org/tpl1.1/record/kew-17547					Arecaceae	Astrocaryum	0.91	malybo	1									Accepted	Astrocaryum malybo	H.Karst.	species	http://www.theplantlist.org/tpl1.1/record/kew-17547	Astrocaryum malybo	Arecaceae	true	tpl	 	
```

but number 15 becomes less obvious considering there is already an _Astrocaryum malybo_ in the database. so you need to edit things by hand, even for a close-to-perfect match of 0.99.

- skip infraspecific information
- [gtk.Clipboard.set_text](http://www.pygtk.org/pygtk2reference/class-gtkclipboard.html)
- skip genus results
- let user check line-by-line

**Comment by mfrasca** [comment]
this might show what I mean: ca63eae
the data contained simple mistakes like misplaced h, or missing i in double ii, things like that.
with the help of TNRS, of the ~350 cases, we went down to 9.

**Comment by mfrasca** [comment]
I'm not so sure this what you mentioned is the same, or just similar to, the lookup functionality at http://tnrs.iplantcollaborative.org/TNRSapp.html
this one is quite good, the only missing thing is the web-api.
without a web-api, the user would need do a couple of manual steps, not so terrible according to me:
- select the things to check (this in any case)
- export with a report that will just print the genus and species epithets.
- open the above page
- paste the output into the search form
- submit list
- wait
- download results
- import the results into Bauble

what is missing?
- the export, "report that will just print the genus and species epithets".
- the import, the TNRS results.
- show a report informing the user about success and failures of the import.
- the graphical interface to all this

**Comment by RoDuth** [comment]
This, and the related issues, are looking really good @mfrasca .... 

I definitely agree that you need to let the user somehow "tick off" any recommended corrections line by line as you need to allow the user to disagree...regardless of source and reliability...  We can be a fickle bunch :smile:  

And to gain all that authorship data that I am normally so slack about entering will be great!  Such a help for those of us that struggle to get the time we would like to spend on our records.  If I can see that all but 20 of the names in my database are accepted by tnrs then its only 20 names I need to look into... not 900+!

Haven't been on GitHub much lately (hope to get more time for it in the new year) so its great to see you have really run with this idea! :+1:

**Comment by mfrasca** [comment]
the "tick off", let me please rely on the user doing it after downloading the file and before stepping back to Bauble. otherwise it's a lot more programming. _sooner or later_ maybe. not now.

**Comment by mfrasca** [comment]
(I did the tick off, and it was not the most complicated thing. this #239 is).

**Comment by mfrasca** [comment]
still missing:
choose the file (you now have to type the path)
connect the synonym/accepted lines...

when you accept something which is considered a synonym, you are accepting both the synonym and the accepted names. this should show in the selection pane. when you decide you are NOT accepting the accepted name, you are also not accepting the synonym. but you can accept the accepted name and leave the synonym out.

**Comment by mfrasca** [comment]
oh, and the ok button should not be active until you reach the last page

**Comment by mfrasca** [comment]
in case of trouble, please reopen or file a new issue.
