### ISSUE TITLE
infraspecific ranks are lexicografically sorted

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#232]
when you insert infraspecific information in a species, the pop down menu for the ranks is sorted lexicographically, ['cv.', 'f.', 'subf.', 'subsp.', 'subvar', 'var.'], while you want them in rank order, ['subsp.', 'var.', 'subvar.', 'f.', 'subf.', 'cv.', ]

**Comment by mfrasca** [comment]
![screenshot from 2015-12-22 08 51 11](https://cloud.githubusercontent.com/assets/122869/11956876/8aedff76-a88b-11e5-9ac8-0772be514106.png)

**Comment by mfrasca** [comment]
empty should be first of the list
![screenshot from 2015-12-22 08 51 11](https://cloud.githubusercontent.com/assets/122869/11956876/8aedff76-a88b-11e5-9ac8-0772be514106.png)

**Comment by mfrasca** [comment]
@RoDuth in case you like 'cv.' **before** real ranks, feel free to reopen.

**Comment by RoDuth** [comment]
No need, thats great cv. should be last in my books...
