### ISSUE TITLE
QueryBuilder to remember last query

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#238]
in a comment to #36, @RoDuth writes:
> In general I think the search functions are one of the big strengths of Bauble and the query builder is great for a layman like myself. I always thought that it would be good if the query builder could stay where you last had it each time you open it and have a clear button to reset it. So that you could use it to generate a search then open it back up and its in the same place you left it so you can add extra criteria to "narrow the search" so to speak.

my behaviour relating to the above is to have the QB construct a query then I edit it by hand and do not go back to the QB unless I need a completely different search.

**Comment by RoDuth** [comment]
I agree, I also tend to edit by hand but I have a couple of scenarios where returning to the previous state would be handy.  Assuming its no harder than clicking the reset button to clear it anyway.
* When I'm trying to find the best approach to get the results I'm looking for I often use the query builder to "fish" for domains/expressions/properties that work.  It would be good to open back up to where I last was so I can "fish" again from the same place.  There are lots of properties that I don't remember unless I use them often.
* When using the query builder to design long, ugly, complex search strings with lots of ANDs or ORs (e.g. `accession where plants.location.code like "01.0%" and source.source_detail.name like "SGAP%" or source.source_detail.name like "Irene%" and plants.quantity > "0"`) I often will "build" them in stages, checking at each stage that I am getting closer to what I am looking for.  Nothing more frustrating than entering one of these long strings and getting a "couldn't find anything for.." result and then having to work out which bit went wrong.
* To narrow the result by adding one more expression. (e.g. in the above example it hadn't occurred to me that I would also get dead accessions and so I had to add the `and plants.quantity > "0"`, maybe a bad example as this would be a simple hand edit but you get the point)  I think this narrowing of the search is the main benefit really.  The others are kind of related.

**Comment by mfrasca** [comment]
This issue was moved to Ghini/ghini.desktop#132
