### ISSUE TITLE
More linking options in the info pane

### ISSUE THREAD

**Issue by RoDuth** [Bauble/bauble.classic#259]
In reference to the hyper-links that are available in the info pane.  I find I use this function a lot and find it an extremely quick way to navigate the data but there are a few pieces of data that don't exist in the info pane that I would like and some data that is there but not a hyper-link.
e.g.:
 * Link to a genus from a species (e.g. if I am looking at *Cupaniopsis ​wadsworthii* I would like to be able to click *Cupaniopsis* to see what other species I have in my records)
 * Link to the Family from species, accession and plant (Family is not currently present in these, could it be in brackets in smaller text below the species name in a species info pane or in brackets beside the species name in accession and plant?  And linked.)
 * Link to source from accession (Source -> **Name:** XYZ Nursery,  XYZ Nursery should be a link to something like `contact where name = 'XYZ Nursery'`)
 * Link to “planting date” from a plant (to consider for the future?see issue #233)

**Comment by mfrasca** [comment]
thanks for opening this one!

**Comment by mfrasca** [comment]
it was marked in the code as open issue. ;)
```
        # TODO: how do we put the genus in a seperate label so it
        # can be clickable but still respect the text wrap to wrap
        # around and indent from the genus name instead of from the
        # species name
```

**Comment by mfrasca** [comment]
@RoDuth what do you expect as link for planting date? all that has been planted on that date?

**Comment by mfrasca** [comment]
@RoDuth what would you say that this is already enough. there are no direct links from plant and accession to genus and family, but from both plant as well as accession you can jump to the species and from there you move on.

**Comment by mfrasca** [comment]
by the way, this link to source_detail/contact also addresses and removes some urgency from the issue #166 raised by @sehrgut.

**Comment by mfrasca** [comment]
I moved the `planting_date` part to #233, so if @RoDuth finds this good enough we can close the issue.

**Comment by mfrasca** [comment]
with feedback by @RoDuth
> what you have done here is exactly what I am looking for.  I would like to have had the genus and family links in accession and plant (family more than anything), but really you are right, one more click is no major delay in the work flow so I can accept it and am happy for you to waste no more time on it for such a trivial want.

and after fc9bd75831649d943c0b434cd1476258bd854d18 I'm closing this one.

**Comment by RoDuth** [comment]
the source link keeps getting stuck.  In the image below, I open Bauble >  search *Agathis robusta* > expand it > select the accession 2011.0001 > click the source contact (Kirisit Nursery) then > search *Cupaniopsis wadsworthii* > expand it > select the accession 2013.0002 > click the source contact and still get Kirisit Nursery
![link to source fault](https://cloud.githubusercontent.com/assets/15710055/12216408/eb4f7f9e-b72b-11e5-81a9-afad87d0e625.png)

**Comment by mfrasca** [comment]
oh. I think this is because I've changed policy and I'm trying to re-use all visual elements, while Brett had it mostly create them anew. I need a bit more bookkeeping this way.

**Comment by mfrasca** [comment]
I had not noticed this, because I had only one donor-contact in my test data.

**Comment by RoDuth** [comment]
Thanks, all fine now.
