### ISSUE TITLE
Unable to delete photos

### ISSUE THREAD

**Issue by felipead87** [Bauble/bauble.classic#30]
It is not possible to delete pictures from picture tab nor notes tab without adding a different photo.

**Comment by mfrasca** [comment]
more detailed:
when you delete a picture (or a note for that matters), the button "accept" will not become active, making it impossible to save changes (the deletion of a note or a picture).

a workaround for the time being:
go to the notes tab.
delete the note corresponding to the picture
insert a new dummy note.
set the category
(at this point the 'accept' button should be active)
remove the dummy note.
accept

**Comment by mfrasca** [comment]
incuded in 1.0.21
run `bauble-update` as usual.
