### ISSUE TITLE
make accession ID format institution-dependent

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#59]
_From @mfrasca on April 29, 2015 21:5_

different gardens use different ID formats for accessions.
in Mompox we just adopted the Bauble standard (year+4.digit) and it served us good,
but here at the JBQ in Quito they already have a 6.digit code for accessions.
at the BTUU in Utrecht they use still an other (much longer) format.

it would be practical if one could specify the accession code format in the institution definition.
the input should then be validated against the format. (maybe an other issue?)

_Copied from original issue: mfrasca/bauble.classic#84_

**Comment by mfrasca** [comment]
also compare with Ghini/ghini.desktop#9. the current list is not from ITF2, the field has an ITF2 description.

**Comment by mfrasca** [comment]
with the limitation that the `###` part must be the trailing part.

**Comment by RoDuth** [comment]
I have a situation here where we have decided that the first part of the current accession number system must represent the year that the accession (physical item) entered the gardens.  So if we planted the plant in late December and I am only now getting time to enter them into the database I am having to change the 2016.xxxx to 2015.xxxx  This means I then have to work out the next number in the sequence.  A minor nuisance but it would be nice if bauble offered the next in the sequence as a kind of auto-fill option.  Also, for all older plants that I am back accessioning, to denote that we don't know exactly when they were planted we give them four capital letter x, as in XXXX, as the first section of the accession number so the accession number looks literally like this XXXX.1098 so the same issue applies here.  Every accession (and this is one of the big task I am on at the moment) I enter with the XXXX accession number I have to remember what the last number was.

Will what your suggesting provide a solution for this scenario?

**Comment by mfrasca** [comment]
yes, it definitely would. it does not offer you the option "previous year", but you can edit the formats so you keep `%Y.####` for this year, `XXXX.####` for the unknown year, and a moving one for the previous year. I would not want to do make things more complicated than necessary, with things like `%{Y-1}.####`. I'm just asking you to edit once a year the 'previous year' code format.

**Comment by mfrasca** [comment]
you can already try it out, you need install ghini-1.0 and checkout and install ghini-1.0-dev.
or wait that I publish 1.0.56.

**Comment by mfrasca** [comment]
I can support the format `%{Y-1}.####`, if it does not look ugly to you, that is.

**Comment by RoDuth** [comment]
Looks really good!
