### ISSUE TITLE
implement 'complex' concept

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#61]
_From @mfrasca on April 29, 2015 21:15_

a complex is some sort of an extra taxonomic level, unrecognized officially but very helpful in identification.
one groups taxa at the same rank in a complex and indicates one of the taxa as the representing one.
this is generally done at the rank of species or genus.
when one identifies an accession to the representing taxon of a complex, the question arises whether this identification is sensu stricto (that is, you really mean that taxon) or sensu lato (that is, you really mean the complex the taxon identifies).

_Copied from original issue: mfrasca/bauble.classic#86_

**Comment by mfrasca** [comment]
please compare to https://en.wikipedia.org/wiki/Clade

**Comment by mfrasca** [comment]
I think this is the same as 'aggregate' / 'segregate' (ITF2-C10)
reading the ITF2 document, is not clear to me and I would like to see some examples.
from interviews I had collected in Quito, but without comparing them to the ITF2 document, I understood that the three strings (that I now find back in C10) apply partially to a taxon (to specify whether the taxon is an aggregate), partially to an identification to such a taxon.
Bauble now has all of them in the taxon definition and you need two different taxa if you want to identify an accession sensu lato c.q. sensu stricto.
I would remove s.str. and s.lat. from the taxon definition, only to keep aggregate as a boolean flag, then when an accession refers to an aggregate taxon you have the option to specify whether the sense of the identification is wide or strict.
@RoDuth you have time to comment?

**Comment by RoDuth** [comment]
@mfrasca I'm not the best person to answer this I have never had call to use this feature.  Maybe @tmyersdn has has a better idea?

**Comment by tmyersdn** [comment]
@mfrasca 

I will take these questions (1) "complex vs aggregate/segregate"  & (2) "removing sensu lato/stricto" to a good taxonomist friend I have here.

**Comment by mfrasca** [comment]
ok. thanks. "remove" more in the sense of "move to accession identification", as I tried to express above.

**Comment by tmyersdn** [comment]
@mfrasca
(1) TDWG in the following schema show a preference for "aggregate":
http://www.tdwg.org/fileadmin/_migrated/content_uploads/v101.xsd
TaxonomicRankGenusSubdivisionEnum">
-<xs:enumeration value="aggr">
<xs:documentation>[aggr.] -- species aggregate
Wikipedia discusses species complex vs aggregate. https://en.wikipedia.org/wiki/Species_complex

(2) I am fine with moving sensu lato / stricto / amplo to accessions

**Comment by mfrasca** [comment]
interesting link and it does answer the question, but it opens an other one... what are these?
&lt;xs:enumeration value="**original**"/>&lt;xs:enumeration value="**revision**"/>&lt;xs:enumeration value="**incomplete**"/>&lt;xs:enumeration value="aggregate"/>&lt;xs:enumeration value="**nominal**"/>
???

**Comment by mfrasca** [comment]
![untitled](https://cloud.githubusercontent.com/assets/122869/12530611/fbf72604-c1b1-11e5-992a-01527b18a79f.png)

should the 'agg.' precede or follow the author?

**Comment by tmyersdn** [comment]
after the author, based on three examples:

http://link.springer.com/article/10.1023%2FA%3A1008617631367
http://archive.bsbi.org.uk/Wats12p1.pdf
http://onlinelibrary.wiley.com/doi/10.1111/j.1095-8339.1993.tb00343.x/abstract

**Comment by tmyersdn** [comment]
@mfrasca, above you ask about the meaning of "original", "revision", "incomplete" and "nominal". 
These are described on page three of the document at link
http://wiki.tdwg.org/twiki/pub/TNC/EarlyDiscussionOnRelationshipTypes/tdwg_tcs.doc

see section 2.2 "(Taxonomic) concept" [page 3] for more explanation

"Original		
The first representation/original publication of a taxon concept/name use. In other words: concepts where a new name has been created. The definition of the taxon concept will be variable depending on where and when it was published. These concepts act as the foundation on which current taxonomic concepts are based.

Revision
A concept definition presented as part of a taxonomic revision. Usually the results of a re-classification (e.g. combining or splitting) of existing concepts where a previously used name is redefined in some way.

Incomplete
An incomplete record of a concept. This should be used if it is known (or suspected) that not all information about the concept is contained in the data source.

Aggregate
A collection of TaxonConcepts grouped together under a name of utility by a user/author. It needs to include links to all of the TaxonConcepts it covers explicitly stated. 
Nomenclatural	A concept holding purely nomenclatural information, any relationships held will be to similar nomenclatural concepts. It (implicitly) covers all concepts that ever used the particular name. A special case of this is a vernacular concept.

Empty
No contents other than its ID (a GUID), which is to be used as a reference to an external TaxonConcept record."

**Comment by mfrasca** [comment]
ok. sound quite irrelevant to identification, that is, as far as the software is concerned.
thanks!

**Comment by tmyersdn** [comment]
yes, I believe these details are more helpful to institutions involved with naming plants, whereas we are more interested in using correct names.
