### ISSUE TITLE
Ubicaciónes duplicadas

### ISSUE THREAD

**Issue by Josy1996** [Bauble/bauble.classic#72]
Hay unas ubicaciónes (las ubicaciónes en IF y IC) que coinciden. Por favor eliminar los duplicados.
Por ejemplo: IF3E, IF-3E.

**Comment by mfrasca** [comment]
in the Location Editor, we could have a 'merge with location' button:
it would allow you choose an other location and merge the two, and solve the conflicts in name and description.

**Comment by mfrasca** [comment]
imagine location id 141 should be merged with 142:

    bauble=> update plant set location_id=142 where location_id=141;
    bauble=> delete from plant_change where from_location_id=141;
    bauble=> delete from location where id=141;

**Comment by mfrasca** [comment]
too many do do it by hand and not practical in the future, I have programmed the interface to merge locations.
